name: ngencerf-server

services:
  redis:
    image: redis:7.2
    container_name: ngencerf-redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis.conf.prod:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    restart: no  # Do not auto-restart Redis on crash or daemon restart. Does NOT force recreation on deploy.
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  ngencerf-services:
    depends_on:
      redis:
        condition: service_healthy
    build:
      dockerfile: ./Dockerfile.production-pw
      context: .
      args:
        - DATA_ASSIMILATION_REF=${DATA_ASSIMILATION_REF:-development}
        - EWTS_REF=${EWTS_REF:-development}
        - MSW_MGR_REF=${MSW_MGR_REF:-development}
        - NGEN_REF=${NGEN_REF:-development}
        - NGEN_FORCING_REF=${NGEN_FORCING_REF:-development}
        - CACHE_BUST=${CACHE_BUST:-1}
    image: ghcr.io/ngwpc/ngencerf-server:${NGENCERF_SERVER_TAG:-latest}
    pull_policy: always
    ports:
      - "8000:8000"
    volumes:
      - ../data/.ngencerf-init:/ngencerf/ngencerf-server/.init/
      - ${NGEN_CAL_DATA_PATH}:/ngencerf/data/
      - ../logs/ngencerf-server:/ngencerf/ngencerf-server/logs/
      - ${CONTAINER_PATH}:/ngencerf/containers/
      - /var/run/docker.sock:/var/run/docker.sock
      - /ngencerf-app/aws:/root/.aws:ro
    environment:
      - NGEN_CAL_DATA_PATH=${NGEN_CAL_DATA_PATH:-/ngencerf-app/data/ngen-cal-data/}
      - NGENCERF_UI_TAG=${NGENCERF_UI_TAG:-latest}
    env_file:
      - path: ./cerfServer/.env-docker-prod
        required: true
      - path: cerfServer/.env-override
        required: true
    privileged: true
